#!/bin/zsh

# Open a new terminal
cmd - return : open -n -a "WezTerm"

# Change window focus
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# Change display focus
alt - s : yabai -m display --focus west
alt - d : yabai -m display --focus east

# Change window space
ctrl + alt - q : yabai -m window --space 1
ctrl + alt - w : yabai -m window --space 2
ctrl + alt - e : yabai -m window --space 3
ctrl + alt - r : yabai -m window --space 4
ctrl + alt - t : yabai -m window --space 5
ctrl + alt - z : yabai -m window --space 6
ctrl + alt - u : yabai -m window --space 7
ctrl + alt - i : yabai -m window --space 8