#!/bin/zsh

# Open a new terminal
cmd - return : open -n -a "WezTerm"

# Change window focus
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# Change display focus
alt - s : yabai -m display --focus west
alt - d : yabai -m display --focus east